/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Igor' at '24.10.16 16:20' with Gradle 2.14.1
 *
 * @author Igor, @date 24.10.16 16:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
